#!/bin/bash

# Environments to build
ENVIRONMENTS="std big"

# Get current version
version=`cat espurna/config/version.h | grep APP_VERSION | awk '{print $3}' | sed 's/"//g'`
echo $version

# Create output folder
mkdir -p firmware

# Build all the required firmwares
for environment in $ENVIRONMENTS; do
    platformio run -e $environment
    mv .pioenvs/$environment/firmware.bin firmware/espurna-$version-$environment.bin
done

platformio run -vv -t uploadfs -e $environment
mv .pioenvs/$environment/spiffs.bin firmware/espurna-$version-spiffs.bin
